const express = require('express');
const Square = require('square');
const app = express();
app.use(express.json());

const squareClient = new Square.Client({
  environment: Square.Environment.Sandbox,
  accessToken: process.env.SQUARE_ACCESS_TOKEN,
});

app.post('/process-payment', async (req, res) => {
  const { nonce } = req.body; // Payment nonce generated by Square payment form

  try {
    const response = await squareClient.paymentsApi.createPayment({
      sourceId: nonce,
      amountMoney: {
        amount: 1000, // $10.00 charge
        currency: 'USD'
      },
      idempotencyKey: 'unique_key_for_this_transaction'
    });

    res.json({ success: true, payment: response.result.payment });
  } catch (error) {
    res.status(500).json({ success: false, error: error.errors });
  }
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`Server listening on port ${PORT}`);
});
